# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.user.user_response_factory:
        class: AppBundle\Api\User\UserResponseFactory

    user_repository:
        class: AppBundle\User\UserRepository
        arguments:
            - '@doctrine.orm.entity_manager'
